spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/TCT2001/all-sample-microservice.git
          clone-on-start: true
          search-paths: shared

server:
  port: 8888
